### PR TITLE
New React based project 

### PR DESCRIPTION
**Pull request by Udit-singh**
All files are been committed.

### CODE REVIEW

**Comment by ajayns** [comment]
This project is primarily for collecting beginner learning projects. This seems like a bit too complex as an example. 
Also, I wouldn't want to include projects that are someone else's without their permission. Is this project built by you? If so, please share the repo.

**Comment by Udit-singh** [comment]
Definitely build by myself
Here the Repo https://github.com/Udit-singh/Covid-19_Tracker

**Comment by ajayns** [comment]
Ahh okay, just clarifying. Anyways the project imo seems a little too complex for a starter project. Maybe if you could trip it down to just illustrating once functionality with react for ex: charts, or testing etc that'd be a valuable addition. Else I wouldn't want to confuse people with a full fledged project in this

**Comment by Udit-singh** [comment]
okay, no problem I can understand.

**Pull request closed without merging**
